window.NEEYAT_DATA = {
  accounts: [
    { role: "Consumer", email: "consumer@neeyat.demo", password: "Demo123!", name: "Maliha", route: "consumer" },
    { role: "Influencer", email: "influencer@neeyat.demo", password: "Demo123!", name: "Amina Green", route: "influencerDashboard" },
    { role: "Business", email: "business@neeyat.demo", password: "Demo123!", name: "KindThread Co.", route: "businessDashboard" },
    { role: "Administrator", email: "admin@neeyat.demo", password: "Demo123!", name: "Neeyat Admin", route: "admin" },
  ],
  retailers: ["EcoCart UK", "KindMarket", "Everyday Better", "Conscious Basket", "Value & Values"],
  categories: ["Fashion", "Beauty", "Household", "Electronics", "Food & Drink", "Personal Care", "Accessories"],
  products: [
    ["Recycled Cotton Hoodie", "Fashion", "KindThread", 42, [88, 91, 78, 82, 76], ["GOTS pending", "Recycled fibres"], "Strong labour disclosure with recycled-material focus."],
    ["Organic Everyday T-Shirt", "Fashion", "North Loom", 18, [82, 84, 72, 79, 70], ["Organic cotton"], "Affordable wardrobe basic with good sourcing visibility."],
    ["Repairable Denim Jacket", "Fashion", "Mend Studio", 64, [79, 86, 75, 88, 68], ["Repair programme"], "Higher price, stronger circularity and repair commitment."],
    ["Vegan Lip Balm", "Beauty", "SoftKind", 5, [76, 74, 81, 83, 72], ["Vegan formula"], "Low-cost beauty product with clear ingredient notes."],
    ["Refill Shampoo Bar", "Beauty", "Bare Bottle", 8, [90, 77, 70, 93, 74], ["Plastic-free"], "Packaging-light option with strong environmental score."],
    ["Mineral Sunscreen SPF30", "Beauty", "ClearRay", 14, [74, 71, 83, 76, 69], ["Cruelty-free"], "Balanced personal-care choice with transparent claims."],
    ["Concentrated Laundry Sheets", "Household", "Neat Home", 11, [92, 72, 76, 91, 73], ["Low packaging"], "Low-waste household product with compact shipping."],
    ["Reusable Cleaning Kit", "Household", "LoopNest", 24, [89, 78, 80, 88, 77], ["Refillable"], "Reusable household kit with strong packaging responsibility."],
    ["Compostable Sponges", "Household", "EarthCupboard", 6, [85, 70, 67, 84, 66], ["Compostable"], "Good-value low-waste household option."],
    ["Refurbished Smartphone", "Electronics", "AgainTech", 189, [91, 73, 82, 87, 78], ["Refurbished"], "Circular electronics option with warranty and strong value."],
    ["Modular Earbuds", "Electronics", "FairSignal", 69, [77, 76, 79, 86, 71], ["Repairable"], "Repairable design improves lifecycle responsibility."],
    ["Low-Energy Desk Lamp", "Electronics", "BrightLite", 32, [83, 68, 73, 80, 67], ["Energy efficient"], "Lower energy consumption with moderate transparency."],
    ["Fairtrade Coffee Beans", "Food & Drink", "BeanEthic", 9, [78, 89, 81, 72, 86], ["Fairtrade"], "Strong labour and certification confidence."],
    ["Plant-Based Protein Mix", "Food & Drink", "RootFuel", 21, [84, 73, 74, 76, 70], ["Plant based"], "Good climate profile with moderate evidence coverage."],
    ["Organic Snack Box", "Food & Drink", "GoodCrate", 16, [75, 70, 69, 73, 68], ["Organic"], "Convenient option with improving transparency."],
    ["Bamboo Toothbrush Pack", "Personal Care", "MouthKind", 7, [86, 72, 71, 89, 70], ["Plastic-free"], "Low-cost personal-care swap with reduced packaging."],
    ["Period Care Refill Box", "Personal Care", "CareCycle", 12, [81, 78, 83, 84, 75], ["Organic cotton"], "Recurring essentials with clear ingredient information."],
    ["Sensitive Skin Soap", "Personal Care", "SimpleOrigin", 4, [73, 76, 79, 78, 67], ["Palm-oil policy"], "Affordable personal-care choice with transparent sourcing notes."],
    ["Cork Card Holder", "Accessories", "CarryKind", 15, [87, 75, 72, 82, 65], ["Vegan material"], "Durable accessory with lower-impact material choice."],
    ["Recycled Backpack", "Accessories", "PackLoop", 38, [89, 80, 74, 86, 72], ["Recycled polyester"], "Strong practical value and recycled materials."],
    ["Solar Travel Charger", "Accessories", "SunPocket", 29, [82, 69, 70, 79, 64], ["Solar assist"], "Useful travel product with moderate data confidence."],
    ["Cotton Baby Sleepsuit", "Fashion", "LittleKind", 19, [80, 87, 76, 78, 73], ["Organic cotton"], "Family-focused product with good labour positioning."],
    ["Aluminium-Free Deodorant", "Beauty", "FreshRoot", 7, [77, 72, 78, 82, 70], ["Refill option"], "Personal-care product with refill pathway."],
    ["Reusable Food Wraps", "Household", "WrapWell", 10, [91, 71, 69, 90, 66], ["Reusable"], "Simple household swap reducing single-use packaging."],
    ["Second-Life Tablet", "Electronics", "AgainTech", 149, [88, 70, 80, 84, 76], ["Refurbished"], "Lower-cost electronics option with circular-economy benefit."],
    ["Rainforest Cocoa", "Food & Drink", "BeanEthic", 6, [76, 86, 84, 71, 82], ["Fairtrade"], "Ethical treat with stronger labour/certification signal."],
    ["Reusable Razor", "Personal Care", "CareCycle", 23, [84, 74, 76, 88, 68], ["Plastic-free"], "Higher upfront cost offset by reusable design."],
    ["Recycled Laptop Sleeve", "Accessories", "PackLoop", 18, [85, 76, 73, 83, 69], ["Recycled fibres"], "Practical accessory with good material responsibility."],
    ["Ethical Tea Selection", "Food & Drink", "GoodCrate", 12, [74, 83, 78, 70, 77], ["Fair sourcing"], "Good labour score with accessible pricing."],
    ["Refill Handwash Bottle", "Household", "Bare Bottle", 9, [88, 73, 74, 90, 72], ["Refillable"], "Clear packaging reduction benefit for everyday use."],
  ].map((item, index) => {
    const [name, category, brand, basePrice, scores, certifications, summary] = item;
    const [environment, labour, governance, responsibility, evidence] = scores;
    const id = `prod-${String(index + 1).padStart(2, "0")}`;
    const listings = window.NEEYAT_DATA?.retailers ? [] : [];
    return {
      id,
      name,
      category,
      brand,
      image: `https://picsum.photos/seed/neeyat-${index + 1}/640/480`,
      basePrice,
      scores: { environment, labour, governance, responsibility, evidence },
      certifications,
      summary,
      dataPoints: 5 + (index % 7),
      verified: index % 3 !== 0,
      selfReported: index % 4 === 0,
      reviewedDaysAgo: 14 + index * 3,
    };
  }),
  influencers: [
    { name: "Amina Green", focus: "Low-waste homes", followers: "42k", engagement: "6.8%", verified: true, collection: "Plastic-light weekly shop" },
    { name: "Sarah Values", focus: "Fair fashion", followers: "31k", engagement: "5.9%", verified: true, collection: "Capsule wardrobe swaps" },
    { name: "Zara Conscious", focus: "Beauty and personal care", followers: "58k", engagement: "7.4%", verified: true, collection: "Refill bathroom shelf" },
    { name: "Imran Impact", focus: "Family budgeting", followers: "24k", engagement: "4.6%", verified: false, collection: "Ethical choices under £20" },
    { name: "Nadia Nour", focus: "Halal-conscious lifestyle", followers: "39k", engagement: "6.1%", verified: true, collection: "Transparent everyday essentials" },
    { name: "Leo Circular", focus: "Refurbished tech", followers: "27k", engagement: "5.2%", verified: true, collection: "Second-life electronics" },
    { name: "Maya Market", focus: "Sustainable food", followers: "33k", engagement: "5.7%", verified: false, collection: "Fairtrade pantry" },
    { name: "Tom Traceable", focus: "Brand transparency", followers: "18k", engagement: "4.9%", verified: true, collection: "Brands that disclose more" },
  ],
  businessAnalytics: {
    views: 12840,
    saves: 932,
    retailerClicks: 1874,
    ctr: "14.6%",
    profileCompleteness: 78,
    subscriptionPlan: "Growth - £99/mo",
  },
  adminStats: {
    users: 6420,
    consumers: 5980,
    influencers: 86,
    businesses: 142,
    products: 312,
    retailerListings: 1218,
    affiliateClicks: 18640,
    estimatedTransactions: 742,
    subscriptionRevenue: 18340,
  },
};
